server:
  port: 8080
    
#management endpoints on a separate port
management:
  port: 8090
  security:
    enabled: false # management port is internal only. no need to secure it.
    
user.service:
  name: 'default profile:'
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
    hibernate:
      ddl-auto: create-drop
  jpa:
    defer-datasource-initialization: true
    show-sql: true
        
user.service:
  name: 'test profile:'